name: ai_cv_library
description: This is a package for image recognition. It can be used with flutter for Android and iOS applications.
version: 1.0.0
homepage: https://github.com/dotic/ai-cv-library
repository: https://github.com/dotic/ai-cv-library
publish_to: 'none'

environment:
  sdk: '>=3.1.2 <4.0.0'

# Add regular dependencies here.
dependencies:
  aws_client: ^0.4.2
  encrypt: ^5.0.3
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  http: ^1.1.2
  image: ^4.1.3
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.4
  intl: ^0.19.0
  native_opencv:
    path: native_opencv
  onnxruntime: ^1.1.0
  open_file_plus: ^3.4.1
  path_provider: ^2.1.1
  tflite_flutter: ^0.10.2
  tuple: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
