#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

NAME=$(git describe --tags --exact-match 2>/dev/null || git symbolic-ref -q --short HEAD)

BRANCH_CHECK="^(all|client-service|connect-(field-store|services))\/(chore|enhancement|feat|feature|fix|hotfix|release)\/[a-z0-9]+(?:-[a-z0-9]+)*"
SEMVER_CHECK="^(0|([1-9][0-9]*))\.(0|([1-9][0-9]*))\.(0|([1-9][0-9]*)).*"
(echo "${NAME}" | grep -Eq "(${BRANCH_CHECK})|(${SEMVER_CHECK})") || (echo "Your branch or tag is incorrect: ${NAME}" && exit 1)
